CREATE DATABASE IF NOT EXISTS boukir;
USE boukir;

CREATE TABLE IF NOT EXISTS employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom_complet VARCHAR(255) DEFAULT NULL,
  cin VARCHAR(16) NOT NULL UNIQUE,
  date_embauche DATE DEFAULT NULL,
  role ENUM('PDG','Employé') DEFAULT NULL,
  password VARCHAR(255) NOT NULL,
  created_by INT NULL,
  updated_by INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
