-- Insert an initial Hero Slide (FR only)
-- Notes:
-- - Multilingual columns *_ar/_en/_zh stay NULL
-- - Kept as draft to avoid runtime/public eligibility rules

INSERT INTO ecommerce_hero_slides (
  type,
  status,
  priority,
  locale,
  starts_at,
  ends_at,
  image_url,
  image_alt,
  title,
  title_ar,
  title_en,
  title_zh,
  subtitle,
  subtitle_ar,
  subtitle_en,
  subtitle_zh,
  description,
  description_ar,
  description_en,
  description_zh,
  category_id,
  brand_id,
  product_id,
  variant_id,
  campaign_id,
  ctas,
  created_by_employee_id,
  updated_by_employee_id
) VALUES (
  'category',
  'draft',
  0,
  'fr',
  NULL,
  NULL,
  '/uploads/hero_slides/hero-1769458868906-297973690.jpg',
  'Hero slide',
  'Bienvenue sur Boukir',
  NULL,
  NULL,
  NULL,
  'Découvrez nos produits',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  1,
  NULL,
  NULL,
  NULL,
  NULL,
  JSON_ARRAY(JSON_OBJECT('label','Voir','style','primary')),
  NULL,
  NULL
);
