CREATE TABLE IF NOT EXISTS bons_charge (
  id INT NOT NULL AUTO_INCREMENT,
  date_creation DATETIME NOT NULL,
  client_id INT NOT NULL,
  phone VARCHAR(50) NULL,
  adresse_livraison VARCHAR(255) NULL,
  montant_total DECIMAL(12,2) NOT NULL DEFAULT 0,
  statut VARCHAR(50) NOT NULL DEFAULT 'En attente',
  observations TEXT NULL,
  created_by INT NULL,
  updated_by INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_bons_charge_client_id (client_id),
  KEY idx_bons_charge_date_creation (date_creation),
  CONSTRAINT fk_bons_charge_client FOREIGN KEY (client_id) REFERENCES contacts(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS charge_items (
  id INT NOT NULL AUTO_INCREMENT,
  bon_charge_id INT NOT NULL,
  product_id INT NULL,
  variant_id INT NULL,
  unit_id INT NULL,
  product_snapshot_id INT NULL,
  designation_custom VARCHAR(255) NOT NULL,
  quantite DECIMAL(12,4) NOT NULL DEFAULT 0,
  prix_achat DECIMAL(12,4) NOT NULL DEFAULT 0,
  cout_revient DECIMAL(12,4) NOT NULL DEFAULT 0,
  prix_gros DECIMAL(12,4) NOT NULL DEFAULT 0,
  prix_unitaire DECIMAL(12,4) NOT NULL DEFAULT 0,
  remise_pourcentage DECIMAL(12,4) NOT NULL DEFAULT 0,
  remise_montant DECIMAL(12,4) NOT NULL DEFAULT 0,
  total DECIMAL(12,4) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_charge_items_bon_charge_id (bon_charge_id),
  KEY idx_charge_items_product_id (product_id),
  KEY idx_charge_items_variant_id (variant_id),
  KEY idx_charge_items_unit_id (unit_id),
  KEY idx_charge_items_product_snapshot_id (product_snapshot_id),
  CONSTRAINT fk_charge_items_bon FOREIGN KEY (bon_charge_id) REFERENCES bons_charge(id) ON DELETE CASCADE,
  CONSTRAINT fk_charge_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
  CONSTRAINT fk_charge_items_variant FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE SET NULL,
  CONSTRAINT fk_charge_items_unit FOREIGN KEY (unit_id) REFERENCES product_units(id) ON DELETE SET NULL,
  CONSTRAINT fk_charge_items_snapshot FOREIGN KEY (product_snapshot_id) REFERENCES product_snapshot(id) ON DELETE SET NULL
);
